[package]
name = "papokin-gametest"
version.workspace = true
description = "Minecraft GameTest framework for Pumpkin."
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
papokin-data = { workspace = true, features = ["block"] }
papokin-macros.workspace = true
papokin-nbt.workspace = true
papokin-util.workspace = true
papokin-world.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
