//! 配方属性集与切石机选项的静态数据（1.21.2+ 配方同步）。
//!
//! `ClientboundUpdateRecipesPacket`（1.21.2 起）由两段组成：
//! - **itemSets**：7 个配方属性集（烧炼/营火输入、锻造三槽），
//!   客户端配方书的「只显示可合成」过滤与熔炉/锻造台 UI 的
//!   输入判定都以此为准；
//! - **stonecutterRecipes**：切石机选项列表（输入原料 → 结果
//!   物品堆），驱动切石机 UI 的结果网格。
//!
//! 本表的线序与内容逐字节取自 Papo 1.21.11 实抓
//! （UPDATE_RECIPES，全长 2819B，经 vanilla 编解码器解码核对）；
//! 以物品名存储，发送时经 [`crate::item_id_remap`] 换算到客户端
//! 版本的冻结 id 空间。

/// 配方属性集：`(注册名, 物品名列表)`，按线序排列。
pub const RECIPE_PROPERTY_SETS: &[(&str, &[&str])] = &[
    (
        "minecraft:smoker_input",
        &[
            "rabbit", "beef", "mutton", "potato", "kelp", "porkchop", "salmon", "cod", "chicken",
        ],
    ),
    (
        "minecraft:campfire_input",
        &[
            "rabbit", "beef", "mutton", "potato", "kelp", "porkchop", "salmon", "cod", "chicken",
        ],
    ),
    (
        "minecraft:smithing_base",
        &[
            "diamond_sword",
            "diamond_nautilus_armor",
            "netherite_chestplate",
            "golden_chestplate",
            "diamond_shovel",
            "diamond_helmet",
            "diamond_spear",
            "copper_leggings",
            "iron_helmet",
            "leather_helmet",
            "netherite_boots",
            "netherite_leggings",
            "diamond_horse_armor",
            "chainmail_leggings",
            "leather_leggings",
            "golden_helmet",
            "diamond_axe",
            "copper_helmet",
            "leather_chestplate",
            "iron_chestplate",
            "copper_boots",
            "leather_boots",
            "chainmail_boots",
            "netherite_helmet",
            "chainmail_helmet",
            "diamond_chestplate",
            "diamond_leggings",
            "diamond_boots",
            "chainmail_chestplate",
            "diamond_pickaxe",
            "iron_boots",
            "diamond_hoe",
            "turtle_helmet",
            "iron_leggings",
            "golden_boots",
            "copper_chestplate",
            "golden_leggings",
        ],
    ),
    (
        "minecraft:furnace_input",
        &[
            "pink_terracotta",
            "mangrove_log",
            "stripped_dark_oak_wood",
            "iron_boots",
            "netherrack",
            "kelp",
            "flowering_azalea_leaves",
            "coal_ore",
            "yellow_terracotta",
            "copper_helmet",
            "stripped_jungle_wood",
            "stripped_cherry_wood",
            "deepslate_redstone_ore",
            "golden_helmet",
            "copper_chestplate",
            "cod",
            "ancient_debris",
            "iron_horse_armor",
            "rabbit",
            "acacia_log",
            "chorus_fruit",
            "stripped_oak_log",
            "diamond_ore",
            "iron_spear",
            "stripped_birch_wood",
            "cherry_leaves",
            "cactus",
            "sand",
            "jungle_log",
            "stripped_mangrove_log",
            "orange_terracotta",
            "nether_bricks",
            "nether_gold_ore",
            "salmon",
            "birch_log",
            "copper_pickaxe",
            "golden_sword",
            "deepslate_iron_ore",
            "pale_oak_log",
            "gold_ore",
            "acacia_leaves",
            "copper_nautilus_armor",
            "stripped_pale_oak_wood",
            "chainmail_chestplate",
            "emerald_ore",
            "magenta_terracotta",
            "stripped_acacia_log",
            "iron_pickaxe",
            "porkchop",
            "copper_spear",
            "cherry_log",
            "deepslate_emerald_ore",
            "clay",
            "stripped_jungle_log",
            "quartz_block",
            "acacia_wood",
            "pale_oak_wood",
            "iron_helmet",
            "golden_leggings",
            "basalt",
            "iron_ore",
            "red_sandstone",
            "deepslate_copper_ore",
            "mutton",
            "deepslate_lapis_ore",
            "stone",
            "resin_clump",
            "clay_ball",
            "jungle_leaves",
            "deepslate_diamond_ore",
            "green_terracotta",
            "blue_terracotta",
            "raw_iron",
            "black_terracotta",
            "copper_horse_armor",
            "stripped_acacia_wood",
            "iron_axe",
            "golden_chestplate",
            "iron_shovel",
            "chainmail_boots",
            "copper_boots",
            "raw_copper",
            "golden_pickaxe",
            "iron_sword",
            "jungle_wood",
            "iron_leggings",
            "mangrove_leaves",
            "oak_wood",
            "mangrove_wood",
            "gray_terracotta",
            "potato",
            "copper_shovel",
            "iron_nautilus_armor",
            "cobblestone",
            "red_terracotta",
            "oak_log",
            "lapis_ore",
            "stripped_spruce_wood",
            "golden_nautilus_armor",
            "spruce_log",
            "nether_quartz_ore",
            "purple_terracotta",
            "stripped_pale_oak_log",
            "deepslate_tiles",
            "copper_hoe",
            "copper_sword",
            "chicken",
            "sandstone",
            "iron_chestplate",
            "stripped_mangrove_wood",
            "azalea_leaves",
            "stripped_dark_oak_log",
            "lime_terracotta",
            "dark_oak_log",
            "spruce_leaves",
            "golden_axe",
            "copper_axe",
            "stripped_spruce_log",
            "light_blue_terracotta",
            "stripped_oak_wood",
            "stripped_birch_log",
            "cyan_terracotta",
            "stone_bricks",
            "raw_gold",
            "stripped_cherry_log",
            "spruce_wood",
            "sea_pickle",
            "golden_spear",
            "polished_blackstone_bricks",
            "pale_oak_leaves",
            "birch_leaves",
            "copper_ore",
            "golden_shovel",
            "wet_sponge",
            "light_gray_terracotta",
            "iron_hoe",
            "birch_wood",
            "deepslate_bricks",
            "cobbled_deepslate",
            "redstone_ore",
            "dark_oak_wood",
            "deepslate_gold_ore",
            "oak_leaves",
            "golden_boots",
            "deepslate_coal_ore",
            "dark_oak_leaves",
            "red_sand",
            "beef",
            "chainmail_helmet",
            "copper_leggings",
            "cherry_wood",
            "golden_hoe",
            "golden_horse_armor",
            "chainmail_leggings",
            "brown_terracotta",
            "white_terracotta",
        ],
    ),
    (
        "minecraft:smithing_addition",
        &[
            "copper_ingot",
            "iron_ingot",
            "emerald",
            "lapis_lazuli",
            "gold_ingot",
            "resin_brick",
            "redstone",
            "netherite_ingot",
            "diamond",
            "quartz",
            "amethyst_shard",
        ],
    ),
    (
        "minecraft:blast_furnace_input",
        &[
            "chainmail_boots",
            "golden_horse_armor",
            "emerald_ore",
            "raw_gold",
            "golden_spear",
            "copper_sword",
            "iron_horse_armor",
            "golden_shovel",
            "iron_axe",
            "copper_hoe",
            "raw_copper",
            "iron_shovel",
            "copper_pickaxe",
            "deepslate_lapis_ore",
            "chainmail_leggings",
            "golden_pickaxe",
            "golden_boots",
            "deepslate_gold_ore",
            "iron_boots",
            "iron_ore",
            "iron_pickaxe",
            "deepslate_copper_ore",
            "deepslate_coal_ore",
            "deepslate_redstone_ore",
            "golden_helmet",
            "chainmail_helmet",
            "copper_shovel",
            "golden_nautilus_armor",
            "chainmail_chestplate",
            "deepslate_iron_ore",
            "copper_axe",
            "iron_leggings",
            "raw_iron",
            "nether_quartz_ore",
            "diamond_ore",
            "copper_helmet",
            "golden_leggings",
            "copper_chestplate",
            "golden_chestplate",
            "nether_gold_ore",
            "redstone_ore",
            "iron_chestplate",
            "golden_hoe",
            "iron_nautilus_armor",
            "copper_leggings",
            "ancient_debris",
            "golden_sword",
            "copper_horse_armor",
            "copper_nautilus_armor",
            "copper_spear",
            "coal_ore",
            "iron_spear",
            "gold_ore",
            "iron_sword",
            "iron_hoe",
            "deepslate_diamond_ore",
            "iron_helmet",
            "copper_boots",
            "lapis_ore",
            "copper_ore",
            "golden_axe",
            "deepslate_emerald_ore",
        ],
    ),
    (
        "minecraft:smithing_template",
        &[
            "flow_armor_trim_smithing_template",
            "ward_armor_trim_smithing_template",
            "host_armor_trim_smithing_template",
            "vex_armor_trim_smithing_template",
            "coast_armor_trim_smithing_template",
            "wayfinder_armor_trim_smithing_template",
            "silence_armor_trim_smithing_template",
            "tide_armor_trim_smithing_template",
            "eye_armor_trim_smithing_template",
            "snout_armor_trim_smithing_template",
            "raiser_armor_trim_smithing_template",
            "bolt_armor_trim_smithing_template",
            "shaper_armor_trim_smithing_template",
            "spire_armor_trim_smithing_template",
            "rib_armor_trim_smithing_template",
            "sentry_armor_trim_smithing_template",
            "netherite_upgrade_smithing_template",
            "wild_armor_trim_smithing_template",
            "dune_armor_trim_smithing_template",
        ],
    ),
];

/// 切石机选项：`(输入物品名集合, 结果物品名, 结果数量)`，按线序排列。
/// 原版同步中 SelectableRecipe 的 recipe 字段全部为空（客户端
/// 只需选项展示），故仅保留输入与结果。
pub const STONECUTTER_OPTIONS: &[(&[&str], &str, u8)] = &[
    (&["andesite"], "andesite_slab", 2),
    (&["andesite"], "andesite_stairs", 1),
    (&["andesite"], "andesite_wall", 1),
    (&["blackstone"], "blackstone_slab", 2),
    (&["blackstone"], "blackstone_stairs", 1),
    (&["blackstone"], "blackstone_wall", 1),
    (&["bricks"], "brick_slab", 2),
    (&["bricks"], "brick_stairs", 1),
    (&["bricks"], "brick_wall", 1),
    (&["copper_block"], "chiseled_copper", 4),
    (&["cut_copper"], "chiseled_copper", 1),
    (&["cobbled_deepslate"], "chiseled_deepslate", 1),
    (&["nether_bricks"], "chiseled_nether_bricks", 1),
    (&["blackstone"], "chiseled_polished_blackstone", 1),
    (&["polished_blackstone"], "chiseled_polished_blackstone", 1),
    (&["quartz_block"], "chiseled_quartz_block", 1),
    (&["red_sandstone"], "chiseled_red_sandstone", 1),
    (&["resin_bricks"], "chiseled_resin_bricks", 1),
    (&["sandstone"], "chiseled_sandstone", 1),
    (&["stone_bricks"], "chiseled_stone_bricks", 1),
    (&["stone"], "chiseled_stone_bricks", 1),
    (&["polished_tuff"], "chiseled_tuff_bricks", 1),
    (&["tuff_bricks"], "chiseled_tuff_bricks", 1),
    (&["tuff"], "chiseled_tuff_bricks", 1),
    (&["tuff"], "chiseled_tuff", 1),
    (&["cobbled_deepslate"], "cobbled_deepslate_slab", 2),
    (&["cobbled_deepslate"], "cobbled_deepslate_stairs", 1),
    (&["cobbled_deepslate"], "cobbled_deepslate_wall", 1),
    (&["cobblestone"], "cobblestone_slab", 2),
    (&["cobblestone"], "cobblestone_stairs", 1),
    (&["cobblestone"], "cobblestone_wall", 1),
    (&["copper_block"], "copper_grate", 4),
    (&["copper_block"], "cut_copper", 4),
    (&["copper_block"], "cut_copper_slab", 8),
    (&["cut_copper"], "cut_copper_slab", 2),
    (&["copper_block"], "cut_copper_stairs", 4),
    (&["cut_copper"], "cut_copper_stairs", 1),
    (&["red_sandstone"], "cut_red_sandstone", 1),
    (&["cut_red_sandstone"], "cut_red_sandstone_slab", 2),
    (&["red_sandstone"], "cut_red_sandstone_slab", 2),
    (&["sandstone"], "cut_sandstone", 1),
    (&["cut_sandstone"], "cut_sandstone_slab", 2),
    (&["sandstone"], "cut_sandstone_slab", 2),
    (&["dark_prismarine"], "dark_prismarine_slab", 2),
    (&["dark_prismarine"], "dark_prismarine_stairs", 1),
    (&["cobbled_deepslate"], "deepslate_brick_slab", 2),
    (&["deepslate_bricks"], "deepslate_brick_slab", 2),
    (&["polished_deepslate"], "deepslate_brick_slab", 2),
    (&["cobbled_deepslate"], "deepslate_brick_stairs", 1),
    (&["deepslate_bricks"], "deepslate_brick_stairs", 1),
    (&["polished_deepslate"], "deepslate_brick_stairs", 1),
    (&["cobbled_deepslate"], "deepslate_brick_wall", 1),
    (&["deepslate_bricks"], "deepslate_brick_wall", 1),
    (&["polished_deepslate"], "deepslate_brick_wall", 1),
    (&["cobbled_deepslate"], "deepslate_bricks", 1),
    (&["polished_deepslate"], "deepslate_bricks", 1),
    (&["cobbled_deepslate"], "deepslate_tile_slab", 2),
    (&["deepslate_bricks"], "deepslate_tile_slab", 2),
    (&["deepslate_tiles"], "deepslate_tile_slab", 2),
    (&["polished_deepslate"], "deepslate_tile_slab", 2),
    (&["cobbled_deepslate"], "deepslate_tile_stairs", 1),
    (&["deepslate_bricks"], "deepslate_tile_stairs", 1),
    (&["deepslate_tiles"], "deepslate_tile_stairs", 1),
    (&["polished_deepslate"], "deepslate_tile_stairs", 1),
    (&["cobbled_deepslate"], "deepslate_tile_wall", 1),
    (&["deepslate_bricks"], "deepslate_tile_wall", 1),
    (&["deepslate_tiles"], "deepslate_tile_wall", 1),
    (&["polished_deepslate"], "deepslate_tile_wall", 1),
    (&["cobbled_deepslate"], "deepslate_tiles", 1),
    (&["deepslate_bricks"], "deepslate_tiles", 1),
    (&["polished_deepslate"], "deepslate_tiles", 1),
    (&["diorite"], "diorite_slab", 2),
    (&["diorite"], "diorite_stairs", 1),
    (&["diorite"], "diorite_wall", 1),
    (&["end_stone_bricks"], "end_stone_brick_slab", 2),
    (&["end_stone"], "end_stone_brick_slab", 2),
    (&["end_stone_bricks"], "end_stone_brick_stairs", 1),
    (&["end_stone"], "end_stone_brick_stairs", 1),
    (&["end_stone_bricks"], "end_stone_brick_wall", 1),
    (&["end_stone"], "end_stone_brick_wall", 1),
    (&["end_stone"], "end_stone_bricks", 1),
    (&["exposed_copper"], "exposed_chiseled_copper", 4),
    (&["exposed_cut_copper"], "exposed_chiseled_copper", 1),
    (&["exposed_copper"], "exposed_copper_grate", 4),
    (&["exposed_copper"], "exposed_cut_copper", 4),
    (&["exposed_copper"], "exposed_cut_copper_slab", 8),
    (&["exposed_cut_copper"], "exposed_cut_copper_slab", 2),
    (&["exposed_copper"], "exposed_cut_copper_stairs", 4),
    (&["exposed_cut_copper"], "exposed_cut_copper_stairs", 1),
    (&["granite"], "granite_slab", 2),
    (&["granite"], "granite_stairs", 1),
    (&["granite"], "granite_wall", 1),
    (&["mossy_cobblestone"], "mossy_cobblestone_slab", 2),
    (&["mossy_cobblestone"], "mossy_cobblestone_stairs", 1),
    (&["mossy_cobblestone"], "mossy_cobblestone_wall", 1),
    (&["mossy_stone_bricks"], "mossy_stone_brick_slab", 2),
    (&["mossy_stone_bricks"], "mossy_stone_brick_stairs", 1),
    (&["mossy_stone_bricks"], "mossy_stone_brick_wall", 1),
    (&["mud_bricks"], "mud_brick_slab", 2),
    (&["mud_bricks"], "mud_brick_stairs", 1),
    (&["mud_bricks"], "mud_brick_wall", 1),
    (&["nether_bricks"], "nether_brick_slab", 2),
    (&["nether_bricks"], "nether_brick_stairs", 1),
    (&["nether_bricks"], "nether_brick_wall", 1),
    (&["oxidized_copper"], "oxidized_chiseled_copper", 4),
    (&["oxidized_cut_copper"], "oxidized_chiseled_copper", 1),
    (&["oxidized_copper"], "oxidized_copper_grate", 4),
    (&["oxidized_copper"], "oxidized_cut_copper", 4),
    (&["oxidized_copper"], "oxidized_cut_copper_slab", 8),
    (&["oxidized_cut_copper"], "oxidized_cut_copper_slab", 2),
    (&["oxidized_copper"], "oxidized_cut_copper_stairs", 4),
    (&["oxidized_cut_copper"], "oxidized_cut_copper_stairs", 1),
    (&["andesite"], "polished_andesite", 1),
    (&["andesite"], "polished_andesite_slab", 2),
    (&["polished_andesite"], "polished_andesite_slab", 2),
    (&["andesite"], "polished_andesite_stairs", 1),
    (&["polished_andesite"], "polished_andesite_stairs", 1),
    (&["basalt"], "polished_basalt", 1),
    (&["blackstone"], "polished_blackstone_brick_slab", 2),
    (
        &["polished_blackstone_bricks"],
        "polished_blackstone_brick_slab",
        2,
    ),
    (
        &["polished_blackstone"],
        "polished_blackstone_brick_slab",
        2,
    ),
    (&["blackstone"], "polished_blackstone_brick_stairs", 1),
    (
        &["polished_blackstone_bricks"],
        "polished_blackstone_brick_stairs",
        1,
    ),
    (
        &["polished_blackstone"],
        "polished_blackstone_brick_stairs",
        1,
    ),
    (&["blackstone"], "polished_blackstone_brick_wall", 1),
    (
        &["polished_blackstone_bricks"],
        "polished_blackstone_brick_wall",
        1,
    ),
    (
        &["polished_blackstone"],
        "polished_blackstone_brick_wall",
        1,
    ),
    (&["blackstone"], "polished_blackstone_bricks", 1),
    (&["polished_blackstone"], "polished_blackstone_bricks", 1),
    (&["blackstone"], "polished_blackstone", 1),
    (&["blackstone"], "polished_blackstone_slab", 2),
    (&["polished_blackstone"], "polished_blackstone_slab", 2),
    (&["blackstone"], "polished_blackstone_stairs", 1),
    (&["polished_blackstone"], "polished_blackstone_stairs", 1),
    (&["blackstone"], "polished_blackstone_wall", 1),
    (&["polished_blackstone"], "polished_blackstone_wall", 1),
    (&["cobbled_deepslate"], "polished_deepslate", 1),
    (&["cobbled_deepslate"], "polished_deepslate_slab", 2),
    (&["polished_deepslate"], "polished_deepslate_slab", 2),
    (&["cobbled_deepslate"], "polished_deepslate_stairs", 1),
    (&["polished_deepslate"], "polished_deepslate_stairs", 1),
    (&["cobbled_deepslate"], "polished_deepslate_wall", 1),
    (&["polished_deepslate"], "polished_deepslate_wall", 1),
    (&["diorite"], "polished_diorite", 1),
    (&["diorite"], "polished_diorite_slab", 2),
    (&["polished_diorite"], "polished_diorite_slab", 2),
    (&["diorite"], "polished_diorite_stairs", 1),
    (&["polished_diorite"], "polished_diorite_stairs", 1),
    (&["granite"], "polished_granite", 1),
    (&["granite"], "polished_granite_slab", 2),
    (&["polished_granite"], "polished_granite_slab", 2),
    (&["granite"], "polished_granite_stairs", 1),
    (&["polished_granite"], "polished_granite_stairs", 1),
    (&["tuff"], "polished_tuff", 1),
    (&["polished_tuff"], "polished_tuff_slab", 2),
    (&["tuff"], "polished_tuff_slab", 2),
    (&["polished_tuff"], "polished_tuff_stairs", 1),
    (&["tuff"], "polished_tuff_stairs", 1),
    (&["polished_tuff"], "polished_tuff_wall", 1),
    (&["tuff"], "polished_tuff_wall", 1),
    (&["prismarine_bricks"], "prismarine_brick_slab", 2),
    (&["prismarine_bricks"], "prismarine_brick_stairs", 1),
    (&["prismarine"], "prismarine_slab", 2),
    (&["prismarine"], "prismarine_stairs", 1),
    (&["prismarine"], "prismarine_wall", 1),
    (&["purpur_block"], "purpur_pillar", 1),
    (&["purpur_block"], "purpur_slab", 2),
    (&["purpur_block"], "purpur_stairs", 1),
    (&["quartz_block"], "quartz_bricks", 1),
    (&["quartz_block"], "quartz_pillar", 1),
    (&["quartz_block"], "quartz_slab", 2),
    (&["quartz_block"], "quartz_stairs", 1),
    (&["red_nether_bricks"], "red_nether_brick_slab", 2),
    (&["red_nether_bricks"], "red_nether_brick_stairs", 1),
    (&["red_nether_bricks"], "red_nether_brick_wall", 1),
    (&["red_sandstone"], "red_sandstone_slab", 2),
    (&["red_sandstone"], "red_sandstone_stairs", 1),
    (&["red_sandstone"], "red_sandstone_wall", 1),
    (&["resin_bricks"], "resin_brick_slab", 2),
    (&["resin_bricks"], "resin_brick_stairs", 1),
    (&["resin_bricks"], "resin_brick_wall", 1),
    (&["sandstone"], "sandstone_slab", 2),
    (&["sandstone"], "sandstone_stairs", 1),
    (&["sandstone"], "sandstone_wall", 1),
    (&["smooth_quartz"], "smooth_quartz_slab", 2),
    (&["smooth_quartz"], "smooth_quartz_stairs", 1),
    (&["smooth_red_sandstone"], "smooth_red_sandstone_slab", 2),
    (&["smooth_red_sandstone"], "smooth_red_sandstone_stairs", 1),
    (&["smooth_sandstone"], "smooth_sandstone_slab", 2),
    (&["smooth_sandstone"], "smooth_sandstone_stairs", 1),
    (&["smooth_stone"], "smooth_stone_slab", 2),
    (&["stone_bricks"], "stone_brick_slab", 2),
    (&["stone"], "stone_brick_slab", 2),
    (&["stone_bricks"], "stone_brick_stairs", 1),
    (&["stone"], "stone_brick_stairs", 1),
    (&["stone_bricks"], "stone_brick_wall", 1),
    (&["stone"], "stone_brick_wall", 1),
    (&["stone"], "stone_bricks", 1),
    (&["stone"], "stone_slab", 2),
    (&["stone"], "stone_stairs", 1),
    (&["polished_tuff"], "tuff_brick_slab", 2),
    (&["tuff_bricks"], "tuff_brick_slab", 2),
    (&["tuff"], "tuff_brick_slab", 2),
    (&["polished_tuff"], "tuff_brick_stairs", 1),
    (&["tuff_bricks"], "tuff_brick_stairs", 1),
    (&["tuff"], "tuff_brick_stairs", 1),
    (&["polished_tuff"], "tuff_brick_wall", 1),
    (&["tuff_bricks"], "tuff_brick_wall", 1),
    (&["tuff"], "tuff_brick_wall", 1),
    (&["polished_tuff"], "tuff_bricks", 1),
    (&["tuff"], "tuff_bricks", 1),
    (&["tuff"], "tuff_slab", 2),
    (&["tuff"], "tuff_stairs", 1),
    (&["tuff"], "tuff_wall", 1),
    (&["waxed_copper_block"], "waxed_chiseled_copper", 4),
    (&["waxed_cut_copper"], "waxed_chiseled_copper", 1),
    (&["waxed_copper_block"], "waxed_copper_grate", 4),
    (&["waxed_copper_block"], "waxed_cut_copper", 4),
    (&["waxed_copper_block"], "waxed_cut_copper_slab", 8),
    (&["waxed_cut_copper"], "waxed_cut_copper_slab", 2),
    (&["waxed_copper_block"], "waxed_cut_copper_stairs", 4),
    (&["waxed_cut_copper"], "waxed_cut_copper_stairs", 1),
    (
        &["waxed_exposed_copper"],
        "waxed_exposed_chiseled_copper",
        4,
    ),
    (
        &["waxed_exposed_cut_copper"],
        "waxed_exposed_chiseled_copper",
        1,
    ),
    (&["waxed_exposed_copper"], "waxed_exposed_copper_grate", 4),
    (&["waxed_exposed_copper"], "waxed_exposed_cut_copper", 4),
    (
        &["waxed_exposed_copper"],
        "waxed_exposed_cut_copper_slab",
        8,
    ),
    (
        &["waxed_exposed_cut_copper"],
        "waxed_exposed_cut_copper_slab",
        2,
    ),
    (
        &["waxed_exposed_copper"],
        "waxed_exposed_cut_copper_stairs",
        4,
    ),
    (
        &["waxed_exposed_cut_copper"],
        "waxed_exposed_cut_copper_stairs",
        1,
    ),
    (
        &["waxed_oxidized_copper"],
        "waxed_oxidized_chiseled_copper",
        4,
    ),
    (
        &["waxed_oxidized_cut_copper"],
        "waxed_oxidized_chiseled_copper",
        1,
    ),
    (&["waxed_oxidized_copper"], "waxed_oxidized_copper_grate", 4),
    (&["waxed_oxidized_copper"], "waxed_oxidized_cut_copper", 4),
    (
        &["waxed_oxidized_copper"],
        "waxed_oxidized_cut_copper_slab",
        8,
    ),
    (
        &["waxed_oxidized_cut_copper"],
        "waxed_oxidized_cut_copper_slab",
        2,
    ),
    (
        &["waxed_oxidized_copper"],
        "waxed_oxidized_cut_copper_stairs",
        4,
    ),
    (
        &["waxed_oxidized_cut_copper"],
        "waxed_oxidized_cut_copper_stairs",
        1,
    ),
    (
        &["waxed_weathered_copper"],
        "waxed_weathered_chiseled_copper",
        4,
    ),
    (
        &["waxed_weathered_cut_copper"],
        "waxed_weathered_chiseled_copper",
        1,
    ),
    (
        &["waxed_weathered_copper"],
        "waxed_weathered_copper_grate",
        4,
    ),
    (&["waxed_weathered_copper"], "waxed_weathered_cut_copper", 4),
    (
        &["waxed_weathered_copper"],
        "waxed_weathered_cut_copper_slab",
        8,
    ),
    (
        &["waxed_weathered_cut_copper"],
        "waxed_weathered_cut_copper_slab",
        2,
    ),
    (
        &["waxed_weathered_copper"],
        "waxed_weathered_cut_copper_stairs",
        4,
    ),
    (
        &["waxed_weathered_cut_copper"],
        "waxed_weathered_cut_copper_stairs",
        1,
    ),
    (&["weathered_copper"], "weathered_chiseled_copper", 4),
    (&["weathered_cut_copper"], "weathered_chiseled_copper", 1),
    (&["weathered_copper"], "weathered_copper_grate", 4),
    (&["weathered_copper"], "weathered_cut_copper", 4),
    (&["weathered_copper"], "weathered_cut_copper_slab", 8),
    (&["weathered_cut_copper"], "weathered_cut_copper_slab", 2),
    (&["weathered_copper"], "weathered_cut_copper_stairs", 4),
    (&["weathered_cut_copper"], "weathered_cut_copper_stairs", 1),
];
