interface logging {
    enum level {
        trace,
        debug,
        info,
        warn,
        error,
    }

    /// 记录任意通用日志消息
    log: func(level: level, message: string);
    /// 此函数供 tracing crate 使用。
    log-tracing: func(event: list<u8>);
}
